services:
  web:
    build: .
    image: cicd-app:latest
    container_name: cicd-app
    ports:
      - 5000:80
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    restart: unless-stopped
