apiVersion: v1
kind: ConfigMap
metadata:
  name: kiii-project-mongo-config
  namespace: kiii
data:
  MONGO_INITDB_DATABASE: mydatabase
  MONGO_INITDB_ROOT_USERNAME: root
---
apiVersion: v1
kind: Secret
metadata:
  name: kiii-project-mongo-secret
  namespace: kiii
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD: d293cGFzc3dvcmQxMjMj
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kiii-project-mongo-pvc
  namespace: kiii
  labels:
    app: mongo
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kiii-project-mongo
  namespace: kiii
spec:
  serviceName: kiii-project-mongo-service
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        namespace: kiii
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: kiii-project-mongo-config
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kiii-project-mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: kiii-project-mongo-config
                  key: MONGO_INITDB_DATABASE
          ports:
            - containerPort: 27017
              name: mongo-port
          volumeMounts:
            - name: kiii-project-mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: kiii-project-mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kiii-project-mongo-service
  namespace: kiii
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: mongo-port
  clusterIP: None
