apiVersion: v1
kind: ConfigMap
metadata:
  name: kiii-project-config
  namespace: kiii
data:
  MONGO_HOST: kiii-project-mongo-service.kiii.svc.cluster.local
  MONGO_PORT: "27017"
  MONGO_DATABASE: mydatabase
  MONGO_USERNAME: root
---
apiVersion: v1
kind: Secret
metadata:
  name: kiii-project-secret
  namespace: kiii
type: Opaque
data:
  MONGO_PASSWORD: d293cGFzc3dvcmQxMjMj
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-project-deployment
  namespace: kiii
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kiii-project
  template:
    metadata:
      labels:
        app: kiii-project
    spec:
      containers:
        - name: kiii-project
          image: zheann/kiii-project:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: kiii-project-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: kiii-project-config
                  key: MONGO_PORT
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: kiii-project-config
                  key: MONGO_DATABASE
            - name: MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: kiii-project-config
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kiii-project-secret
                  key: MONGO_PASSWORD
